version: "3.8"

services:
  app:
    build: .
    image: low-res-change-detector:latest
    # mounts the project (code, data, secrets) into the container
    volumes:
      - .:/app
    entrypoint: ["python", "-u"]
    tty: true